options:
  formatter: stylish
files:
  include: 'scss/**/*.scss'
  ignore: 'scss/**/vendor/**/*.scss'
rules:
  border-zero:
    - 2
    -
      convention: 0
  brace-style:
    - 2
    -
      style: 1tbs
      allow-single-line: false
  clean-import-paths:
    - 2
    -
      leading-underscore: false
      filename-extension: false
  empty-args:
    - 2
    -
      include: false
  empty-line-between-blocks:
    - 2
    -
      include: true
      allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline:
    - 2
    -
      include: true
  force-attribute-nesting: 0
  force-element-nesting: 2
  force-pseudo-nesting: 0
  function-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
      convention-explanation: "Function name must be in hyphenatedlowercase format with no leading underscore"
  hex-length:
    - 2
    -
      style: short
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 2
    -
      size: 2
  leading-zero:
    - 2
    -
      include: true
  mixin-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
      convention-explanation: "Mixin name must be in hyphenated-lowercase format with no leading underscore"
  mixins-before-declarations:
    - 2
    -
      exclude: ['breakpoint']
  nesting-depth:
    - 2
    -
      max-depth: 3
  no-color-keywords: 2
  no-color-literals: 0
  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties:
    - 2
    -
      exclude:
        - display
  no-empty-rulesets: 2
  no-extends: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: true
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 2
  no-transition-all: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2
  no-warn: 0
  one-declaration-per-line: 2
  placeholder-in-extend: 2
  placeholder-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
      convention-explanation: "Placeholder name must be in hyphenated-lowercase format with no leading underscore"
  property-sort-order:
    - 2
    -
      order: smacss
      ignore-custom-properties: false
  #property-units:
  #  - 2
  #  -
  #    global: ['em', 'px', 'rem']
  quotes:
    - 2
    -
      style: single
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-bang:
    - 2
    -
      include: false
  space-after-colon:
    - 2
    -
      include: true
  space-after-comma:
    - 2
    -
      include: true
  #space-around-operator:
  #  - 2
  #  -
  #    include: true
  space-before-bang:
    - 2
    -
      include: true
  space-before-brace:
    - 2
    -
      include: true
  space-before-colon:
    - 2
    -
      include: false
  space-between-parens:
    - 2
    -
      include: false
  trailing-semicolon:
    - 2
    -
      include: true
  url-quotes: 2
  variable-for-property: 0
  variable-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
      convention-explanation: "Variable names must be in hyphenated-lowercase format with no leading underscore"
  zero-unit:
    - 2
    -
      include: false
