# SCSS-Lint Configuration
# https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md

linters:

  # Prefer 'border: 0' over 'border: none'
  BorderZero:
    enabled: true

  # Selectors should all be lowercase
  CapitalizationInSelector:
    enabled: true

  # Prefer hexadecimal color codes over color keywords - 'red, green etc.'
  ColorKeyword:
    enabled: true

  # Sass comments are preferred, but CSS comments will be stripped on build
  Comment:
    enabled: false

  # Reports @debug statements which are accidentally left in
  DebugStatement:
    enabled: true

  # Write @extend statements first in rule sets
  DeclarationOrder:
    enabled: true

  # Reports when you define the same property twice in a single rule set. Legacy fallbacks rely on this though (HEX, RGBA etc)
  DuplicateProperty:
    enabled: false

  # Place @else statements on the same line as the preceding curly brace.
  ElsePlacement:
    enabled: true
    style: same_line # or 'new_line'

  # Separate rule, function, and mixin declarations with empty lines.
  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  # Reports when you have an empty rule set.
  EmptyRule:
    enabled: true

  # Files should always have a final newline. This results in better diffs when adding lines to the file, since SCM systems such as git won't think that you touched the last line.
  FinalNewline:
    enabled: true
    present: true

  # You can specify whether you prefer shorthand or long-form hexadecimal colors
  HexLength:
    enabled: true
    style: short # or 'long'

  # Checks if hexadecimal colors are written in lowercase
  HexNotation:
    enabled: true
    style: lowercase # or 'uppercase'

  # Ensure hexadecimal colors are valid (either three or six digits).
  HexValidation:
    enabled: true

  # Don't combine additional selectors with an ID selector.
  IdWithExtraneousSelector:
    enabled: true

  # Default indentation set to tabs instead of spaces
  Indentation:
    enabled: true
    character: space # or 'tab'
    width: 2

  # Don't write leading zeros for numeric values with a decimal point.
  LeadingZero:
    enabled: false
    style: exclude_zero # or 'include_zero'

  # Reports when you define the same selector twice in a single sheet.
  MergeableSelector:
    enabled: true
    force_nesting: true

  # Functions, mixins, and variables should be declared with all lowercase letters and hyphens instead of underscores.
  NameFormat:
    enabled: true
    convention: hyphenated_lowercase # or 'BEM', or a regex pattern

  # Always use placeholder selectors in @extend.
  PlaceholderInExtend:
    enabled: false

  # Sort properties in a strict order.
  PropertySortOrder:
    enabled: true
    order: concentric # defaults to alphabetical
    ignore_unspecified: false

  # Reports when you use an unknown CSS property (ignoring vendor-prefixed properties).
  PropertySpelling:
    enabled: true
    extra_properties: []

  # Reports when you use an unknown CSS property (ignoring vendor-prefixed properties).
  SelectorDepth:
    enabled: true
    max_depth: 3

  # Prefer the shortest shorthand form possible for properties that support it.
  Shorthand:
    enabled: true

  # Properties within rule sets should each reside on their own line.
  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: true

  # Split selectors onto separate lines after each comma.
  SingleLinePerSelector:
    enabled: false

  # Commas in lists should be followed by a space.
  SpaceAfterComma:
    enabled: true

  # Properties should be formatted with a single space separating the colon from the property's value.
  SpaceAfterPropertyColon:
    enabled: true
    style: one_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  # Properties should be formatted with no space between the name and the colon.
  SpaceAfterPropertyName:
    enabled: true

  # Opening braces should be preceded by a single space.
  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false

  # Parentheses should not be padded with spaces.
  SpaceBetweenParens:
    enabled: true
    spaces: 0

  # String literals should be written with single quotes unless using double quotes would save on escape characters.
  StringQuotes:
    enabled: false
    style: single_quotes # or double_quotes

  # Property values, @extend directives, @include directives, and variable declarations should always end with a semicolon.
  TrailingSemicolon:
    enabled: true

  # Numeric values should not contain unnecessary fractional portions.
  UnnecessaryMantissa:
    enabled: true

  # Do not use parent selector references (&) when they would otherwise be unnecessary.
  UnnecessaryParentReference:
    enabled: true

  # URLs should not contain protocols or domain names.
  UrlFormat:
    enabled: true

  # URLs should always be enclosed within quotes.
  UrlQuotes:
    enabled: true

  # Omit length units on zero values.
  ZeroUnit:
    enabled: true

  Compass::*:
    enabled: false
